imports:
  - https://raw.githubusercontent.com/aspnet/benchmarks/main/scenarios/aspnet.profiles.standard.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk2/wrk2.yml
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml
  - https://raw.githubusercontent.com/aspnet/benchmarks/main/docker/redis/redis.yml

variables:
  writeRatio: 0
  contentLength: 64
  keyLength: 16
  cacheCount: 256

jobs:
  distributedcache:
    source:
      repository: https://github.com/aspnet/Benchmarks
      branchOrCommit: main
      project: src/BenchmarksApps/DistributedCache/DistributedCache.csproj
      readyStateText: Application started
      arguments: --WriteRatio {{ writeRatio }} --ContentLength {{ contentLength }} --KeyLength {{ keyLength }} --CacheCount {{ cacheCount }}

scenarios:
  redis:
    db:
      job: redis
    application:
      job: distributedcache
      arguments: --Cache redis --redisEndpoint "{{ databaseServer }}"
    load:
      job: bombardier

  redis_local:
    main:
      job: redis
    application:
      job: distributedcache
      arguments: --Cache redis --redisEndpoint 127.0.0.1
    load:
      job: bombardier

  memory:
    application:
      job: distributedcache
      arguments: --Cache memory
    load:
      job: bombardier

  nullcache:
    application:
      job: distributedcache
      arguments: --Cache null
    load:
      job: bombardier