# Examples:
# --config plaintext.benchmarks.yml --scenario plaintext --profile aspnet-physical
# --config benchmarks.compose.yml --scenario fortunes --profile aspnet-physical

imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true
  - https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/WrkClient/wrk.yml

variables:
  serverPort: 5000

jobs:
  aspnetbenchmarks:
    source:
      repository: https://github.com/aspnet/benchmarks.git
      branchOrCommit: main
      project: src/Benchmarks/Benchmarks.csproj
    readyStateText: Application started.
    variables:
      presetHeaders: plaintext
      serverPort: 5000
      protocol: http
      serverScheme: http
      server: Kestrel
      transport: Sockets
      scenario: plaintext
      database: ''
    arguments: "--nonInteractive true --scenarios {{scenario}} --urls {{serverScheme}}://{{serverAddress}}:{{serverPort}} --server {{server}} --kestrelTransport {{transport}} --protocol {{protocol}} {% if database.size > 0 %} --database {{ database }} {% endif %}"
  
scenarios:
  plaintext:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: plaintext
    load:
      job: wrk
      variables:
        path: /plaintext
        pipeline: 16

  https:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: plaintext
        protocol: https
        serverScheme: https
    load:
      job: wrk
      variables:
        path: /plaintext
        pipeline: 16
        serverScheme: https

  endpoint:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: EndpointPlaintext
    load:
      job: wrk
      variables:
        path: /ep-plaintext
        pipeline: 16

  mvc:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: MvcPlaintext
    load:
      job: wrk
      variables:
        path: /mvc/plaintext
        pipeline: 16

  connectionclose:
    application:
      job: aspnetbenchmarks
      variables:
        scenario: Plaintext
    load:
      job: wrk
      variables:
        path: /plaintext
        pipeline: 0
        presetHeaders: connectionclose
