# Examples:
# --config platform.benchmarks.yml --scenario json --profile aspnet-citrine-lin

imports:
  - https://github.com/aspnet/Benchmarks/blob/main/scenarios/aspnet.profiles.yml?raw=true
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Wrk/wrk.yml

jobs:
  sample:
    source:
      localFolder: .
      project: Template.csproj
    readyStateText: Application started.
    framework: net6.0

scenarios:
  sample:
    application:
      job: sample
    load:
      job: wrk
      variables:
        path: /InvariantCultureIgnoreCase/1234
        serverPort: 5000
        connections: 512
